In [3]:
import pandas as pd

In [9]:
df = pd.read_csv(r"D:\Open Source\Data-Science-Revision\Panda\data_cleaning_sample.csv")

In [11]:
df

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   NaN        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5      NaN  28.0        Delhi      F     eve@domain.com         NaN
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [13]:
df.isnull()

    Name    Age   City  Gender  Email  Join Date
0  False  False  False   False  False      False
1  False   True  False   False  False      False
2  False  False  False   False  False      False
3  False   True  False   False  False      False
4  False  False  False   False  False      False
5   True  False  False   False  False       True
6  False  False  False   False  False      False
7  False  False  False   False  False      False
8  False   True  False   False  False      False

In [15]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Email        0
Join Date    1
dtype: int64

In [17]:
df.dropna()

    Name   Age         City Gender              Email   Join Date
0  Alice  25.0     New York      F  alice@example.com  01-05-2021
2    Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
4  David  22.0       Mumbai      M  david@example.com  12-11-2019
6  Alice  25.0     New York      F  alice@example.com  01-05-2021
7  Alice  25.0     New York      F  alice@example.com  01-05-2021

In [19]:
df.fillna(0)

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie   0.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5        0  28.0        Delhi      F     eve@domain.com           0
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   0.0        Delhi      M    charlie@example  20-07-2021

In [21]:
df['Age'].fillna(df['Age'].mean())

0    25.000000
1    25.833333
2    30.000000
3    25.833333
4    22.000000
5    28.000000
6    25.000000
7    25.000000
8    25.833333
Name: Age, dtype: float64

In [23]:
df.fillna(method = 'ffill')

C:\Users\Lenovo\AppData\Local\Temp\ipykernel_20096\1145651979.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  df.fillna(method = 'ffill')

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  25.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    David  28.0        Delhi      F     eve@domain.com  12-11-2019
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie  25.0        Delhi      M    charlie@example  20-07-2021

In [25]:
df.bfill()

      Name   Age         City Gender              Email   Join Date
0    Alice  25.0     New York      F  alice@example.com  01-05-2021
1  Charlie  30.0        Delhi      M    charlie@example  20-07-2021
2      Bob  30.0  Los Angeles      M    bob@example.com  15-06-2020
3  Charlie  22.0        Delhi      M    charlie@example  20-07-2021
4    David  22.0       Mumbai      M  david@example.com  12-11-2019
5    Alice  28.0        Delhi      F     eve@domain.com  01-05-2021
6    Alice  25.0     New York      F  alice@example.com  01-05-2021
7    Alice  25.0     New York      F  alice@example.com  01-05-2021
8  Charlie   NaN        Delhi      M    charlie@example  20-07-2021

In [27]:
df.duplicated()

0    False
1    False
2    False
3     True
4    False
5    False
6     True
7     True
8     True
dtype: bool

In [57]:
df = df.drop_duplicates()

In [59]:
df

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019
5    26.25  28.00        Delhi      F     eve@domain.com       26.25

In [61]:
df['Age'] = df['Age'].fillna(df['Age'].mean())

In [63]:
df = df.drop(5)

In [65]:
df

      Name    Age         City Gender              Email   Join Date
0    Alice  25.00     New York      F  alice@example.com  01-05-2021
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020
4    David  22.00       Mumbai      M  david@example.com  12-11-2019

In [67]:
df["Name"].str.lower()

0      alice
1    charlie
2        bob
4      david
Name: Name, dtype: object

In [73]:
df["City"].str.contains("Delhi")

0    False
1     True
2    False
4    False
Name: City, dtype: bool

In [75]:
df["Email"].str.split("@")

0    [alice, example.com]
1      [charlie, example]
2      [bob, example.com]
4    [david, example.com]
Name: Email, dtype: object

In [87]:
# Applying Function
df["Age Group"] = df["Age"].apply(lambda x: "Adult" if x > 25 else "Minor")

In [89]:
df

      Name    Age         City Gender              Email   Join Date Age Group
0    Alice  25.00     New York      F  alice@example.com  01-05-2021     Minor
1  Charlie  26.25        Delhi      M    charlie@example  20-07-2021     Adult
2      Bob  30.00  Los Angeles      M    bob@example.com  15-06-2020     Adult
4    David  22.00       Mumbai      M  david@example.com  12-11-2019     Minor

In [91]:
gender_map = {"M": "Male", "F": "Female"}
df["Gender"] = df["Gender"].map(gender_map)

In [93]:
df

,Name,Age,City,Gender,Email,Join Date,Age Group
0,Alice,25.00,New York,Female,alice@example.com,01-05-2021,Minor
1,Charlie,26.25,Delhi,Male,charlie@example,20-07-2021,Adult
2,Bob,30.00,Los Angeles,Male,bob@example.com,15-06-2020,Adult
4,David,22.00,Mumbai,Male,david@example.com,12-11-2019,Minor

In [95]:
df["City"].replace({"Delhi": "New Delhi", "Mumbai": "Bombay"})

0       New York
1      New Delhi
2    Los Angeles
4         Bombay
Name: City, dtype: object