In [1]:
import pandas as pd

In [4]:
df = pd.read_csv(r"D:\Open Source\Data-Science-Revision\Panda\movies_data.csv", encoding_errors = "replace")

In [6]:
df

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score
0,13 Hours,Michael Bay,144,Toby Stephens,James Badge Dale,David Costabile,Action,50000000,69400000,50.00,69.23,19400000,0,0.0,2016,7.4
1,16 Blocks,Richard Donner,102,Bruce Willis,David Zayas,Sasha Roiz,Action,52000000,65000000,33.33,50.00,13000000,0,0.0,2006,6.6
2,17 Again,Burr Steers,102,Matthew Perry,Hunter Parrish,Thomas Lennon,Comedy,20000000,139000000,44.44,25.00,119000000,0,0.0,2009,6.4
3,1982,Tommy Oliver,90,Bokeem Woodbine,Ruby Dee,Quinton Aaron,Drama,1000000,2000000,50.00,100.00,1000000,0,0.0,2013,7.1
4,2 Fast 2 Furious,John Singleton,107,Paul Walker,Cole Hauser,Mo Gallini,Action,76000000,236000000,75.00,42.85,160000000,0,0.0,2003,5.9
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3969,Z Storm,David Lam,92,Michael Wong,Louis Koo,Stephen Au,Action,7000000,17000000,100.00,100.00,10000000,0,0.0,2014,5.3
3970,Zack and Miri Make a Porno,Kevin Smith,101,Gerry Bednob,Jeff Anderson,Jennifer Schwalbach Smith,Comedy,24000000,42000000,66.67,41.66,18000000,0,0.0,2008,6.6
3971,Zero Effect,Jake Kasdan,116,Kim Dickens,Ryan O'Neal,Angela Featherstone,Comedy,5000000,2000000,33.33,50.00,-3000000,0,0.0,1998,7.0
3972,Zombieland,Ruben Fleischer,88,Emma Stone,Bill Murray,Derek Graf,Adventure,23600000,102000000,66.67,33.33,78400000,0,0.0,2009,7.7
3973,Zulu,J�r?me Salle,110,Orlando Bloom,Tanya van Graan,Conrad Kemp,Crime,16000000,5000000,0.00,0.00,-11000000,0,0.0,2013,6.7

In [10]:
df.sort_values('Release year')

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score
3471,The Broadway Melody,Harry Beaumont,100,Anita Page,Bessie Love,Charles King,Romance,379000,40000000,100.00,100.00,39621000,4,3.0,1929,6.3
2654,Hell's Angels,Howard Hughes,96,Jean Harlow,Marian Marsh,James Hall,Drama,3950000,8500000,100.00,100.00,4550000,1,0.0,1930,7.8
3272,She Done Him Wrong,Lowell Sherman,66,Mae West,Gilbert Roland,Louise Beavers,Comedy,200000,2000000,100.00,100.00,1800000,1,0.0,1933,6.5
2000,42nd Street,Lloyd Bacon,89,Ginger Rogers,Dick Powell,George Brent,Comedy,439000,2500000,100.00,100.00,2061000,2,2.0,1933,7.7
1843,It Happened One Night,Frank Capra,65,Claudette Colbert,Alan Hale,Walter Connolly,Comedy,325000,3500000,100.00,60.00,3175000,5,5.0,1934,8.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1752,Hail Caesar!,Ethan Coen,106,Scarlett Johansson,Channing Tatum,Alden Ehrenreich,Comedy,22000000,63000000,88.89,71.42,41000000,3,0.0,2016,6.4
1346,Zoolander 2,Ben Stiller,102,Milla Jovovich,Will Ferrell,Justin Theroux,Comedy,50000000,55900000,50.00,80.00,5900000,0,0.0,2016,4.8
1567,The 5th Wave,J Blakeson,112,Chlo� Grace Moretz,Maggie Siff,Nick Robinson,Action,38000000,108000000,100.00,100.00,70000000,1,0.0,2016,5.2
1560,Suicide Squad,David Ayer,123,Will Smith,Robin Atkin Downes,Ike Barinholtz,Action,175000000,746000000,55.55,71.42,571000000,1,1.0,2016,6.9
1503,Pete's Dragon,David Lowery,102,Bryce Dallas Howard,Oona Laurence,Isiah Whitlock Jr.,Adventure,65000000,143000000,100.00,100.00,78000000,1,0.0,2016,7.3

In [18]:
df = df.sort_values(['Release year','IMDb score'], ascending = False)

In [22]:
df = df.reset_index(drop=True)

In [24]:
df

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score
0,Kickboxer: Vengeance,John Stockwell,90,Matthew Ziff,T.J. Storm,Sam Medina,Action,17000000,3000000,0.00,0.00,-14000000,0,0.0,2016,9.1
1,Airlift,Raja Menon,130,Nimrat Kaur,Sameer Ali Khan,Purab Kohli,Action,4400000,50000000,66.67,100.00,45600000,0,0.0,2016,8.5
2,Captain America: Civil War,Anthony Russo,147,Robert Downey Jr.,Scarlett Johansson,Chris Evans,Action,250000000,1153000000,100.00,50.00,903000000,5,2.0,2016,8.2
3,Deadpool,Tim Miller,108,Ryan Reynolds,Ed Skrein,Stefan Kapicic,Action,58000000,786000000,100.00,100.00,728000000,1,0.0,2016,8.1
4,Mr. Church,Bruce Beresford,104,Mckenna Grace,Lucy Fry,Natalie Coughlin,Drama,8000000,6850000,0.00,66.67,-1150000,0,0.0,2016,8.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3969,It Happened One Night,Frank Capra,65,Claudette Colbert,Alan Hale,Walter Connolly,Comedy,325000,3500000,100.00,60.00,3175000,5,5.0,1934,8.2
3970,42nd Street,Lloyd Bacon,89,Ginger Rogers,Dick Powell,George Brent,Comedy,439000,2500000,100.00,100.00,2061000,2,2.0,1933,7.7
3971,She Done Him Wrong,Lowell Sherman,66,Mae West,Gilbert Roland,Louise Beavers,Comedy,200000,2000000,100.00,100.00,1800000,1,0.0,1933,6.5
3972,Hell's Angels,Howard Hughes,96,Jean Harlow,Marian Marsh,James Hall,Drama,3950000,8500000,100.00,100.00,4550000,1,0.0,1930,7.8
3973,The Broadway Melody,Harry Beaumont,100,Anita Page,Bessie Love,Charles King,Romance,379000,40000000,100.00,100.00,39621000,4,3.0,1929,6.3

In [26]:
df['Rank'] = df['IMDb score'].rank(ascending = False)

In [28]:
df

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score,Rank
0,Kickboxer: Vengeance,John Stockwell,90,Matthew Ziff,T.J. Storm,Sam Medina,Action,17000000,3000000,0.00,0.00,-14000000,0,0.0,2016,9.1,3.0
1,Airlift,Raja Menon,130,Nimrat Kaur,Sameer Ali Khan,Purab Kohli,Action,4400000,50000000,66.67,100.00,45600000,0,0.0,2016,8.5,43.5
2,Captain America: Civil War,Anthony Russo,147,Robert Downey Jr.,Scarlett Johansson,Chris Evans,Action,250000000,1153000000,100.00,50.00,903000000,5,2.0,2016,8.2,114.5
3,Deadpool,Tim Miller,108,Ryan Reynolds,Ed Skrein,Stefan Kapicic,Action,58000000,786000000,100.00,100.00,728000000,1,0.0,2016,8.1,157.5
4,Mr. Church,Bruce Beresford,104,Mckenna Grace,Lucy Fry,Natalie Coughlin,Drama,8000000,6850000,0.00,66.67,-1150000,0,0.0,2016,8.0,216.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3969,It Happened One Night,Frank Capra,65,Claudette Colbert,Alan Hale,Walter Connolly,Comedy,325000,3500000,100.00,60.00,3175000,5,5.0,1934,8.2,114.5
3970,42nd Street,Lloyd Bacon,89,Ginger Rogers,Dick Powell,George Brent,Comedy,439000,2500000,100.00,100.00,2061000,2,2.0,1933,7.7,442.5
3971,She Done Him Wrong,Lowell Sherman,66,Mae West,Gilbert Roland,Louise Beavers,Comedy,200000,2000000,100.00,100.00,1800000,1,0.0,1933,6.5,2098.5
3972,Hell's Angels,Howard Hughes,96,Jean Harlow,Marian Marsh,James Hall,Drama,3950000,8500000,100.00,100.00,4550000,1,0.0,1930,7.8,349.5
3973,The Broadway Melody,Harry Beaumont,100,Anita Page,Bessie Love,Charles King,Romance,379000,40000000,100.00,100.00,39621000,4,3.0,1929,6.3,2401.0

In [32]:
df.sort_values('Rank')

,Movie,Director,Running time,Actor 1,Actor 2,Actor 3,Genre,Budget,Box Office,Actors Box Office %,Director Box Office %,Earnings,Oscar and Golden Globes nominations,Oscar and Golden Globes awards,Release year,IMDb score,Rank
3333,The Shawshank Redemption,Frank Darabont,142,Morgan Freeman,Jeffrey DeMunn,Bob Gunton,Crime,25000000,28000000,50.00,50.00,3000000,7,0.0,1994,9.3,1.0
3840,The Godfather,Francis Ford Coppola,175,Al Pacino,Marlon Brando,Robert Duvall,Crime,6000000,250000000,59.36,72.72,244000000,10,7.0,1972,9.2,2.0
0,Kickboxer: Vengeance,John Stockwell,90,Matthew Ziff,T.J. Storm,Sam Medina,Action,17000000,3000000,0.00,0.00,-14000000,0,0.0,2016,9.1,3.0
1295,The Dark Knight,Christopher Nolan,152,Christian Bale,Heath Ledger,Morgan Freeman,Action,185000000,1000000000,86.66,100.00,815000000,8,2.0,2008,9.0,4.5
3824,The Godfather: Part II,Francis Ford Coppola,220,Robert De Niro,Al Pacino,Robert Duvall,Crime,13000000,57000000,52.69,72.72,44000000,11,6.0,1974,9.0,4.5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1636,Who's Your Caddy?,Don Michael Paul,93,Jeffrey Jones,Faizon Love,Lil' Wayne,Comedy,7000000,5420000,33.33,0.00,-1580000,0,0.0,2007,2.0,3970.0
1478,Disaster Movie,Jason Friedberg,88,Carmen Electra,Tony Cox,Ike Barinholtz,Comedy,25000000,34500000,38.88,50.00,9500000,0,0.0,2008,1.9,3971.5
2170,Superbabies: Baby Geniuses 2,Bob Clark,88,Scott Baio,Vanessa Angel,Peter Wingfield,Comedy,20000000,25000000,0.00,50.00,5000000,0,0.0,2004,1.9,3971.5
761,Foodfight!,Lawrence Kasanoff,91,Jerry Stiller,Larry Miller,Harvey Fierstein,Animation,65000000,73000,0.00,0.00,-64927000,0,0.0,2012,1.7,3973.0
937,Justin Bieber: Never Say Never,Jon M. Chu,115,Usher Raymond,Sean Kingston,Boys II Men,Documentary,13000000,99400000,66.67,100.00,86400000,0,0.0,2011,1.6,3974.0